### ISSUE TITLE
Support environments

### ISSUE THREAD

**Issue by neillturner** [stevenjack/cfndsl#167]
All the config tools like chef, puppet ansible support environments so you can have different parameter values for different environments (i.e. the database connection string will be different from test and live). 
This would be easy to implement in cfndsl and as people are used to environments in these other tools and then it is easy for folks to grasp and use. I found that a feature like this would have been very helpful when i was using the tool. 
So: 
1. add a new parameter -e <environment name>
2. Currently we have parameters with a default value: 
      Default("m1.small") 
   maybe we have another parameter 
     Environment_Default("{"test": "m1.small",
                                          "live":"m3.medium"})
3. Maybe the code will set a system parameter $environment with the environment so this could be used programatically by folks. 
I would be happy to write a PR for this as i don't think it is a large code change. 
Also any suggestions, improvements, better implementations from other folks are very welcome. -)

**Comment by johnf** [comment]
I do this by having an environment's directory which contains a YAML file for each environment. e.g.
``` yaml
# production
web:
  instance: t2.micro
```

I've also been thinking of supporting deep merging of the hashes so you could supply multiple YAML files on the command line.

I like the idea of an environment flag though.

**Comment by gergnz** [comment]
we are working on this at the moment. @geoffreyharrison can supply more details on how this is working.

**Comment by neillturner** [comment]
@johnf perhaps you can explain that to me a bit more. Always interested in learning from others. 
 @geoffreyharrison sounds interesting. I certainly don't want to duplicate what others are doing. 
thanks
@neillturner

**Comment by stevenjack** [comment]
@gergnz / @geoffreyharrison would be great to know what you guys are thinking about this. We had a similar approach to @johnfs at the last place I worked.

@neillturner thinking about the environments side of things, if we had something like:

```ruby
Environment_Default({
  "test" => "m1.small",
  "live"  => "m3.medium"
})
```
or even:

```ruby
Default({
  "test" => "m1.small",
  "live"  => "m3.medium"
})
```

It doesn't really feel right putting environment specific configuration into the template definition, in terms of something like chef you generally have `environments/test|staging|production|.json` and that's used at run time rather than having it in your cookbooks or recipes.

I think the method of having a folder structure like:

```
environments
--test.yml
--staging.yml
--live.yml
```

then in each of the yaml files you have the defaults defined for that environment then you just run:

```
$: cfndsl my_stack.rb -y environments/test.yml`
```

and if you wanted to script it:

```
export ENVIRONMENT=test
cfndsl my_stack.rb -y environments/$ENVIRONMENT.yml`
```

You can also do things like pull the data out of something like vault before generating the `yaml` file and finally creating the template so you're not actually storing you potentially sensitive configuration data in the templates themselves.

Happy to hear everyones thoughts on this though!

**Comment by kornypoet** [comment]
@stevenjack I agree that this should be left up to the end user. It adds more complexity and forces the user to think about another layer of configuration abstraction when they don't have to using plain CloudFormation. Couple that with the fact that implementing environmental config is as easy as separate `.yaml` files or directories and this makes this a questionable benefit at best. My team currently implements environments using naming conventions outside of `cfndsl` and it feels like a natural place to separate library concern from business logic. More methods defined within `cfndsl` isn't going to make environmental config easier to implement.

Chef, puppet, et al are frameworks, while cfndsl is a library. CloudFormation proper doesn't support environments and I don't think cfndsl should either.

**Comment by gergnz** [comment]
@stevenjack I'll try and summarise, but @geoffreyharrison would be best. I'll ping him on Monday to at least double check what I'm saying is valid.

We are using ansble to drive cfndsl and ultimately stand up the the stack. This gives us the flexibility to drive the yaml loaded as you say.  What we also do is load in defaults at each layer. Here's an example:

```
config
|__defaults.yml
|__dev
     |__defaults.yml
     |__Instances
          |__myinstance.yml
|__production
     |__defaults.yml
     |__Instances
          |__myinstance.yml
```
we then can define the environment (either production or dev in this example), and we can load up each yaml with multiple -y e.g.

```
cfndsl -y config/defaults.yml -y {{ environment }}/defaults.yml -y {{ environment }}/Instances/myinstance.yml ...
```
What @johnf is proposing takes this one step further, which would be awesome.  Today if we have an array or hash of items, we have to re-define the whole array or hash. It would be great if we could merge.

Hope that helps.

**Comment by kornypoet** [comment]
That makes sense. Having `cfndsl` support clarified merging behavior would work for both issues I believe. Right now, the library assigns constants to the top level keys in yaml file, and would reassign if passed another file with the same key. 

If `cfndsl` implemented something along the lines of [deep_merge](http://apidock.com/rails/Hash/deep_merge) with an example in the `README` would that cover your use case?

As an aside, I've been working on implementing a config class to handle external parameters, rather than setting constants in a `binding`, a practice which I believe to be a little kludgy. It would be extremely easy to add specific merging behavior to this class if that would be helpful. This class would hopefully also make it easier to handle environments as an end user, because you could access the configuration object as a whole, giving you greater control.

**Comment by kornypoet** [comment]
The issue I referenced in my above comment: stevenjack/cfndsl#170

**Comment by ampedandwired** [comment]
Coincidentally I have recently created [a gem](https://github.com/ampedandwired/bora) which addresses many of the points in this issue, as well as #170 and #117.

To summarize, it provides:
* YAML based configuration
* Support for multiple templates, each with multiple "environments" (stacks)
* Support for plain JSON and cfndsl templates
* Define both cfndsl and CloudFormation parameters inside the YAML config
* Ability to look up values from other stacks on the fly and pass them as parameters into the template
* Command line tool and Rake tasks for working with your templates/environments.
  For example: create/update/delete stack, template diff, validate, events

Anyway I'd be interested in your thoughts: https://github.com/ampedandwired/bora

Happy to help out or contribute code back here if it makes sense. Personally I kind of like the idea of cfndsl remaining a light-weight, composable tool focused just on the DSL. Then other tools can build on top of it in various ways to provide higher-level abstractions such as environments.

**Comment by stevenjack** [comment]
@ampedandwired great work, I've had a similar idea in terms of a number of sub `cfn-xx` gems that deal with environments, inter stack dependencies etc. Seems like `bora` is a great working example of this idea, really like the ability to pull values from one stack to another.

Completely agree on your view of `cfndsl` being exactly what it's name suggest:

> CloudFormation DSL

The more functionality we put in the more dependencies get added in and it starts to become much more than it should be. 

I think configuration for multiple stacks and the [External Parameters](https://github.com/stevenjack/cfndsl/pull/172) still have merit sitting in `cfndsl`. You want to be able to take advantage of being able to parameterise your stacks and provide potentially more complex objects so you can DRY up your templates.

**Comment by cmaxwellau** [comment]
Hi all,

I have a system where all environment specific data is abstracted out into a definitions file which is then included in the rake build. Hoping to be able to share is with the wider world soon as I'm developing it across multiple customers concurrently

Essentially each environment is it's own rake task, this is then used to select which of the environment definitions to use.

I also have coded in some AWS architectural patterns such as autoscaling, static instances, ec2 autorecovery etc that can all be defined on a per-tier basis, and the overridden per environment if necessary. 

This gives me the ability to set defaults and then only specify if otherwise.

This is a pattern that I have defined and have all of my Cloud Architects follow in ANZ on a range of customers from small startups to large enterprises.

As per above, I'm not in a position to share it with the wider world yet but I'm happy to share the thinking behind it :) 

An example rakefile could contain:

```
require 'cfndsl/rake_task'
require 'fileutils'
$purpose = "eComm"
$client = "ATO"
$stringtime  = Time.new.inspect

definitions_file='environment-definitions.rb'

CfnDsl::RakeTask.new('prod2-buildsprint') do |t|
  output_dir = 'output/prod2
  FileUtils.mkpath(output_dir)
  t.cfndsl_opts = {
    verbose: true,
    pretty: true,
    files: [
      { filename: "templates/app-infra.rb", output: "#{output_dir}/app-infrastructure.json" },
      { filename: "templates/vpc.rb", output: "#{output_dir}/vpc.json" },
      { filename: "templates/s3_buckets.rb", output: "#{output_dir}/s3bucket.json" },
      { filename: "templates/awsconfigservice.rb", output: "#{output_dir}/awsconfigservice.json" },
    ],
    extras: [ 
      [:ruby, definitions_file],
      [:raw, "env_name='preprod'"],
      [:raw, "debug_igw=false"],
      [:raw, "connectivity=false"],
  }
end

CfnDsl::RakeTask.new('preprod') do |t|
  output_dir = 'output/preprod/'
  FileUtils.mkpath(output_dir)
  t.cfndsl_opts = {
    verbose: true,
    pretty: true,
    files: [
      { filename: "templates/vpc.rb", output: "#{output_dir}/vpc.json" },
      { filename: "templates/s3_buckets.rb", output: "#{output_dir}/s3bucket.json" },
      { filename: "templates/awsconfigservice.rb", output: "#{output_dir}/awsconfigservice.json" },
    ],
    extras: [ 
      [:ruby, definitions_file],
      [:raw, "env_name='preprod'"],
      [:raw, "debug_igw=false"],
      [:raw, "connectivity=false"],
    ]
  }
end
```
And an example environment-variables could contain:
```
$environments = {
  "prod" => {
    "tiers" => {}, # use default, no overrides
    "VPCs" => {
      "Main" => {
        "CIDR" => "192.168.0.0/20",
        "subnets" => {
          "Core" => {
            "AZa" => "192.168.0.0/24",
            "AZb" => "192.168.1.0/24",
            "AZc" => "192.168.2.0/24",
            "All" => "192.168.0.0/22"
          },
        }
      }, 
    }
  }, # prod

  "preprod" => {
    "tiers" => {
      "Web" => {
        "availability" => {
          "static" => {
            "instances" => [1,0,0],
          }
        },
      },
      "App" => {
        "availability" => {
          "static" => {
            "instances" => [1,0,0],
          }
        },
      },
    }, # Only want one instance 
    "VPCs" => {
      "Main" => {
        "CIDR" => "10.1.0.0/20",
        "subnets" => {
          "eCommerce" => {
            "AZa" => "10.1.0.0/24",
            "AZb" => "10.1.1.0/24",
            "AZc" => "10.1.2.0/24",
            "All" => "10.1.0.0/22"
          },
        }
      },
    } #  /VPCs
  }, # preprod
} # /environments

$tiers = {
  "Web" => {
    "instance_profile" => { "Action" => [ "ec2:Describe*" ], "Effect" => "Allow", "Resource" => "*" },
    "serviceport" => 80, 
    "os" => "windows", 
    "instance_type" => "m4.xlarge",
    "availability" => {
      "static" => {
        "instances" => [2,2,2],
      }
    }
  },
  "App" => {
    "instance_profile" => { "Action" => [ "ec2:Describe*" ], "Effect" => "Allow", "Resource" => "*" },
    "serviceport" => 82, 
    "os" => "windows", 
    "instance_type" => "m4.xlarge",
    "availability" => {
      "elb" => {"scheme" => "internal", "cross_zone" => true, "protocol" => "HTTP", "listenport" => 80}, 
      "static" => {
        "instances" => [2,2,2],
      }
    },
  },
  "DB" => {
    "instance_profile" => { "Action" => [ "ec2:Describe*" ], "Effect" => "Allow", "Resource" => "*" },
    "serviceport" => 1433, 
    "os" => "windows", 
    "instance_type" => "m4.4xlarge",
    "availability" => {
      "static" => {
        "instances" => [1,1,0],
      }
    },
  }
} # tiers

```
Cheers,

Cam

**Comment by zhelyan** [comment]
Here's my experience for what it's worth:

I don't think cfndsl should impose particular config model, the library is already good enough to be integrated and pull parameters from existing configuration management tools or from custom defined config models. 
Until recently I thought exactly the opposite, trying to come up with a silver bullet and nail the configuration so it's right for all my needs:
 
I have been using the `cloudformation-ruby-dsl` for the past 2 years (the examples below are library agnostic). I wanted to have environment, product and stack default parameters so I went for YML configuration and defined a hierarchy. This is the root of all devil, you cannot cover all edge cases. 

The basic idea is that you have this relation: `AWS account 1-* environment 1-* product 1-* tier 1-* stack` defined in yamls (hate yamls):

```yml
# templates/2tier.yml next to 2tier.rb

params:
  MaxSize: 1
  # more
  
userdata: |
 #cloud-config
  output:
    all: '| tee -a /var/log/cloud-init-output.log'
  final_message: 'The system is finally up, after $UPTIME seconds'
  bootcmd:
  - cloud-init-per instance my_set_hostname sh -xc "echo {{ref('Organisation')}}-{{ref('Product')}}-{{ref('Environment')}}-{{ref('Role')}}-$INSTANCE_ID > /etc/hostname; hostname -F /etc/hostname"
  - cloud-init-per instance my_etc_hosts sh -xc "sed -i -e '/^127.0.1.1/d' /etc/hosts; echo 127.0.1.1 {{ref('Organisation')}}-{{ref('Product')}}-{{ref('Environment')}}-{{ref('Role')}}-$INSTANCE_ID >> /etc/hosts"
  .....
  

# templates/rds.yml, rds.rb is in the same folder

params: # precedence 4, lowest
  DBUser: me
  # more
  
  
# config/environments.yml

dev: &default
  metadata:
    aws_profile: dev
    # other stuff
  overrides:  # precedence = 2, globals for all products except if overriden below 
    Owner: devops@company.com
  products:
    cmr: # product name
      db: # tier
        template: rds.rb # searched for recursively 
        overrides:  # highest precedence, overrides env overrides above
          Owner: devteam-db@company.com
        params: # precedence 3, overrides the params in the stack yml
          DBUser: cmr-user
      web:
		template: 2tier.rb
        overrides: {}
        params:
          MaxSize: 2 
		  # etc
	    
prod: 
  <<: *default 
  metadata:
    aws_profile: prod

```

then I can do:

`thor product create cmr -e dev`

or 

`thor environment create dev` etc. 

Having defined a hierarchy I had to deal with recursive merging, validation, coercion etc.
In my case I used `Hashie::Dash` for each level of the hierarchy in order to coerce the yaml e.g:

```ruby

class ConfigBuilder < Hashie::Dash
  # includes here
  
  
  def from_hash(h)
   #
  end
  
  def locate(name, dir, ext=rb)
    #
  end
end

class StackConfig < ConfigBuilder 
    # mappings to the yml config
	property :params, required: true
	property :userdata
end

class Product < ConfigBuilder

    # a product has one or more tiers
    class Tier < ConfigBuilder
      property :template, transform_with: ->(value) { locate(Settings.templates, value) }, required: true
      property :overrides, default: {}
      property :params, default: {}
      property :name, transform_with: -> (value) { value.to_s }
    end
	
	property :tiers, required: true
    property :name, transform_with: -> (value) { value.to_s }
    coerce_key :tiers, ->(value) { value.map do |tier_name, tier_config|
      ::Devops::Product::Tier.from_hash(tier_config.merge(name: tier_name))
    end
    }
	
end

```

Another similar project at https://github.com/envato/stack_master

Hope I managed to show the problem in another perspective.

**Comment by webdevwilson** [comment]
Currently, we are using cumulus (https://github.com/cotdsa/cumulus) to manage the stacks and cfndsl to generate the templates. We have a project that has two rake 'phases':

1. generate cfn templates with cfndsl
2. generate cumulus yaml files for each of our environments
3. apply updates to stacks

This allows us to have one cumulus template that contains the stack(s) definition.

I briefly considered creating a cfndsl_workflow project that built a workflow on top of cfndsl, but I am not convinced that the stack manager should be coupled with the template generator. I agree that cfndsl should remain a simple DSL and other projects should build on top of it.

Enjoying the discussion of how everyone has built workflows around cfndsl. Thanks for sharing!

**Comment by stevenjack** [comment]
@zhelyan Agree with your perspective. I think the emerging responses in this thread is that people are already using numerous tools to provide the config management, inter stack interpolation and other features.

I'm going to close this issue as I think the general consensus here is that the original feature request isn't needed and the current functionality especially with [external parameters](https://github.com/stevenjack/cfndsl/issues/170) gives enough flexibility for others to extends upon.
