### ISSUE TITLE
-D external parameters Readme.md sample does not work

### ISSUE THREAD

**Issue by herebebogans** [stevenjack/cfndsl#196]
The example of using external_parameters.fetch shown in the Readme and in sample/t1.rb does not work with the -D switch.

Example:

```
cfndsl -D "description=a_test_description" ./t1.rb
raw code:1:in eval_file_with_extras: undefined local variable or method 'a_test_description' for CfnDsl:Module (NameError)

```
Interestingly this works

```
cfndsl -p -D "description=description" ./t1.rb
...
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "description",
  "Resources": {
    "machine1": {
      "Properties": {
        "ImageId": "ami-12345678"
      },
      "Type": "AWS::EC2::Instance"
    }
  }
}
```

**Comment by kornypoet** [comment]
When using the `-D` switch in legacy parameter mode, you need to quote your strings, like this:

```
-D "description='a_test_description'"
```

Otherwise you will get the error you got above. I would recommend, however, to disable the binding of parameters to constants by using the `-b` switch. This interpolates variables _only_ in the external parameters hash, and it treats all values as strings. The above command will work as specified this way as well.

```
bin/cfndsl -b -p -D "description=a_test_description" sample/t1.rb
```

**Comment by herebebogans** [comment]
Thanks for the info - that works much better with the -b switch.

I'm not sure the -D switch alone is working as intended.

`cfndsl  -p -D "description='my_test_description'" sample/t1.rb`

contains the single quotes in the generated output
`
{                                          
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "'my_test_description'",  
  "Resources": {                           
    "machine1": {                          
      "Properties": {                      
        "ImageId": "ami-12345678"          
      },                                   
      "Type": "AWS::EC2::Instance"         
    }                                      
  }                                        
}                                         
`

**Comment by herebebogans** [comment]
PS. I've updated the Readme.md with a working example.

**Comment by kornypoet** [comment]
I can see how the behavior would be confusing, however, it is functioning as intended. The legacy behavior was to take the key-value pair from the `-D` flag and evaluate it as raw ruby code. This begets the need for quoting values twice, otherwise ruby won't compile the statement. In the new world, the behavior is to split the key-value pair at the equal sign, and create an entry in the external_parameters hash, with the value always being represented as a string.

The two behaviors don't play very nicely together, as you've seen. It's preferable to pick one over the other, and since the legacy behavior is deprecated, it is recommended that you use the newer behavior always (the `-b` invocation). Knowing that all values will become strings allows you to not worry about getting the quoting correct.

Knowing all this, I think it would be more beneficial to update the `README` with the newer behavior, and omit the quotation fixes. The example will be working again as specified, but will hopefully encourage utilizing the code in the new way.
