### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by gergnz** [stevenjack/cfndsl#199]
Hi @stevenjack,

Wondering if there is anyway we could have some of the community give you hand in maintaining the repo.

I'm happy to put my hand up as I know that maintaining an OSS project can be challenging at time mixed in between family and work commitments.

Cheers.

**Comment by stevenjack** [comment]
hey @gergnz appreciate you opening up this question as it is something I've certainly been up against a few times and as you so rightly put it maintaining an OSS project can be challenging at times :D.

I'm most certainly happy to open up the floor to a discussion about anybody else who would like to be added as contributors to the repository, just add a comment in here and we can take things from there.

Steve

**Comment by kornypoet** [comment]
👍

**Comment by johnf** [comment]
I'd also be interested

**Comment by jstenhouse** [comment]
@stevenjack If you still need any help, I'd be interested.

**Comment by stevenjack** [comment]
@gergnz @kornypoet @johnf I've added you all as collaborators as I've had a hard time keeping up with things due to a number of circumstances, I don't want to see PR's going stale and I think you three have contributed a lot to the repo.

The release process is as follows:

1. Merge PR
2. Pull latest changes down onto local copy of master
3. Run `$: rake bump[patch|minor|major]` which will automatically bump the version in `lib/cfndsl/version.rb`, tag the commit and push everything up
4. Travis will pick up the tagged version and push it up to rubygems

Let me know if you have anymore questions around this.
