### ISSUE TITLE
Usage of CreationPolicy()

### ISSUE THREAD

**Issue by herebebogans** [stevenjack/cfndsl#252]
To create JSON with a resource with CreationPolicy atrribute such as

> "CreationPolicy" : {
>   "AutoScalingCreationPolicy" : {
>     "MinSuccessfulInstancesPercent" : 100
>   },
>   "ResourceSignal" : {    
>     "Count" : 1,
>     "Timeout" : PT15M
>   }
> }

Can only do so by calling CreationPolicy() twice such as

> 
>     CreationPolicy(
>       'ResourceSignal',
>       Count: '1',
>       Timeout: 'PT20M'
>     )
>     CreationPolicy(
>       'AutoScalingCreationPolicy',
>       MinSuccessfulInstancesPercent: '100'
>     )

Not sure how to change creation_policy.rb to make it more like the rest of the DSL eg something like

>     CreationPolicy(
>       ResourceSignal: {
>         Count: '1',
>         Timeout: 'PT15M'
>       },
>       AutoScalingCreationPolicy: {
>         MinSuccessfulInstancesPercent: '100'
>       }
>     )

**Comment by kornypoet** [comment]
It's a similar issue to what I encountered with `Metadata`. The problem here is that `CreationPolicy` is assigned to `Resource` as a `dsl_content_object`. This requires the method invocation to have 2 arguments, and combines all invocations under one object, with each argument pair becoming key-value pairs in a hash. This gives us the guarantee that the CreationPolicy entry in the resulting template is always formatted correctly. Needing multiple entries requires multiple invocations, as you've discovered.

If we change `CreationPolicy` to be assigned to resource as a `dsl_attr_setter`, then the method invocation accepts only one argument, which can be totally free-form. (We would also need to change `UpdatePolicy` as well, to keep all the behavior the same). This is a simple fix, but would break existing implementations.

We decided `Metadata` should be changed because forcing all entries to be a Hash didn't actually line up with the AWS documentation

I feel like this is just a preference choice here. I'm not in favor of this change because it could cause users' templates to fail and because needing to invoke `CreationPolicy` twice works already, and doesn't bother me that greatly to see it in a template. However, I'm _so_ strongly opposed that a couple of yes votes couldn't convince me.

@gergnz ?

**Comment by gergnz** [comment]
@kornypoet, crazy idea...

I want to dump _-b_ as once you have fixed up your templates it's now redundant. I'm also a bit over seeing the add_tag deprecation on every installation (it's like I need to double check a job didn't fail in our builds cause this line pops up at gem install time).

You've discussed refactoring a number of the components and with the recent release of yaml support, we've also discussed refactoring jsonable.

With those in mind, I'd like to do this the *right* way, but in a 1.x release (e.g. breaking changes, not stability... though not sure on the marketing of that).

**Comment by kornypoet** [comment]
Is this concerning CreationPolicy specifically? In general I like the approach, and breaking changes are acceptable on major release versions. So, not really a crazy idea. Probably best for a new thread though.

**Comment by gergnz** [comment]
Not specifically, but we should wind it up into the bigger plans. Sorry for the noise, wanted to kick off the conversation somewhere though.

**Comment by herebebogans** [comment]
Thanks guys - I guess I've got the answer to my question so happy to close this.
