### ISSUE TITLE
Ruby 2.1.0 is minimum required version, but we don't discuss this anywhere

### ISSUE THREAD

**Issue by gergnz** [stevenjack/cfndsl#331]
@zsustar found an issue when installing CFNDSL on EL7 which has ruby 2.0.0p648. Looking at the ruby docs for Psych:Module it looks like safe_load was introduced in 2.1.0.

I suggest we introduce a .ruby-version file and also update the documentation? Can we also specify an minimum version in the gemspec.

**Comment by gergnz** [comment]
```bash
gem install cfndsl-0.14.0.gem
ERROR:  Error installing cfndsl-0.14.0.gem:
        cfndsl requires Ruby version ~> 2.1.
```

**Comment by zsustar** [comment]
Thanks for raising this. I managed to upgreade ruby to 2.1 (also have 2.4 installed on same instance which is managed by rvm)

However I could run this on Ubuntu without same issue, so i will keep on palying on Ubuntu and test on RH later to provide more issue details.

Error ourput from RH 7 + ruby 2.1 + cfndsl 0.15
```
[root@ tmp]# cfndsl test.rb -j  json_pp
The creation of constants as config is deprecated!
Please switch to the #external_parameters method within your templates to access variables
See https://github.com/stevenjack/cfndsl/issues/170
Use the --disable-binding flag to suppress this message
/usr/local/rvm/gems/ruby-2.1.10/gems/cfndsl-0.15.0/lib/cfndsl/external_parameters.rb:62:in `load_file': Unrecognized extension  (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.1.10/gems/cfndsl-0.15.0/lib/cfndsl.rb:67:in `block in eval_file_with_extras'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/cfndsl-0.15.0/lib/cfndsl.rb:62:in `each'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/cfndsl-0.15.0/lib/cfndsl.rb:62:in `eval_file_with_extras'
        from /usr/local/rvm/gems/ruby-2.1.10/gems/cfndsl-0.15.0/bin/cfndsl:128:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/cfndsl:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/cfndsl:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'

[root@ tmp]# ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]

[root@ tmp]# cfndsl --version
cfndsl 0.15.0
```

**Comment by zsustar** [comment]
It turns out the jsonpp is missing from my enviroment, so all good after jsonpp installed.

For any newbie just start the CFNDSL/Ruby journey, conclusion for running cfndsl on AWS RedHat 7:

1. Enable the YUM Option Repo, this is required to install _libyaml_ which is required by the ruby.
 Edit /etc/yum.repos.d/redhat-rhui.repo , and chang _enabled=0_ to  _enabled=1_ in `[rhui-REGION-rhel-server-optional]` section.

2. As the default YUM only provide Ruby 2.0, you need to install RVM (Ruby Version Manager), and use RVM to install Ruby which is required for cfndsl.

Install required package
```
sudo yum install gcc-c++ patch readline readline-devel zlib zlib-devel -y
sudo yum install libyaml-devel libffi-devel openssl-devel make -y
sudo yum install bzip2 autoconf automake libtool bison iconv-devel sqlite-devel -y
```
install RVM as root user
`curl -L get.rvm.io | bash -s stable`

setup rvm env
`source /etc/profile.d/rvm.sh`

Start the ruby installation, following example is installing the latest 2.1.10 version.
`rvm install 2.1`

or version 2.4(2.3 is minimum required for another tools cfn2dsl to convert JSON to )
`rvm install 2.4`

3. Install CSNDSL 
`gem install cfn2dsl`

4. Instal JSONPP
As I am running on RedHat and no Go installed, just copy jsonpp to the $PATH, like /usr/bin should work.
https://jmhodges.github.io/jsonpp/

5. Now you should'd be able to run the first example from cfndsl README.md

6, If you want to convert the JSON format to Ruby, install cfn2dsl
`gem install cfn2dsl`
